### ISSUE TITLE
[BUG] pip install nodestream is accessing /usr/local/LICENSE.txt

### ISSUE THREAD

**Issue by patmoore** [nodestream-proj/nodestream#165]
**Describe the bug**

**To Reproduce**

1. pip install nodestream on MacOSX
2. observe error: ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/usr/local/LICENSE.txt'

OUTPUT from "pip install nodestream"

Collecting nodestream

  Downloading nodestream-0.8.20-py3-none-any.whl.metadata (3.6 kB)

Collecting Jinja2<4,>=3 (from nodestream)

  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 2.2 MB/s eta 0:00:00

Collecting boto3<2.0.0,>=1.26.137 (from nodestream)

  Downloading boto3-1.29.2-py3-none-any.whl.metadata (6.7 kB)

Collecting cleo<3.0.0,>=2.0.1 (from nodestream)

  Downloading cleo-2.1.0-py3-none-any.whl.metadata (12 kB)

Collecting confluent-kafka<3.0.0,>=2.3.0 (from nodestream)

  Downloading confluent_kafka-2.3.0-cp311-cp311-macosx_10_9_x86_64.whl.metadata (2.3 kB)

Collecting cookiecutter<3.0.0,>=2.1.1 (from nodestream)

  Downloading cookiecutter-2.4.0-py3-none-any.whl.metadata (7.0 kB)

Collecting cymple==0.8.1 (from nodestream)

  Downloading cymple-0.8.1-py2.py3-none-any.whl.metadata (7.5 kB)

Collecting httpx<0.25.0,>=0.24.1 (from nodestream)

  Downloading httpx-0.24.1-py3-none-any.whl.metadata (7.4 kB)

Collecting jmespath<2.0.0,>=1.0.1 (from nodestream)

  Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)

Collecting neo4j<6.0.0,>=5.8.0 (from nodestream)

  Downloading neo4j-5.14.1.tar.gz (192 kB)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 192.8/192.8 kB 4.4 MB/s eta 0:00:00

  Installing build dependencies ... done

  Getting requirements to build wheel ... done

  Installing backend dependencies ... done

  Preparing metadata (pyproject.toml) ... done

Collecting pandas<3,>=2 (from nodestream)

  Downloading pandas-2.1.3-cp311-cp311-macosx_10_9_x86_64.whl.metadata (18 kB)

Collecting psutil<6.0.0,>=5.9.6 (from nodestream)

  Downloading psutil-5.9.6-cp36-abi3-macosx_10_9_x86_64.whl.metadata (21 kB)

Collecting python-json-logger<3.0.0,>=2.0.4 (from nodestream)

  Downloading python_json_logger-2.0.7-py3-none-any.whl (8.1 kB)

Requirement already satisfied: pyyaml<7.0,>=6.0 in /usr/local/lib/python3.11/site-packages (from nodestream) (6.0.1)

Collecting schema<0.8.0,>=0.7.5 (from nodestream)

  Downloading schema-0.7.5-py2.py3-none-any.whl (17 kB)

Collecting testcontainers<4.0.0,>=3.7.1 (from testcontainers[neo4j]<4.0.0,>=3.7.1->nodestream)

  Downloading testcontainers-3.7.1-py2.py3-none-any.whl (45 kB)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.3/45.3 kB 1.3 MB/s eta 0:00:00

Collecting uvloop<=0.18.0,>=0.17.0 (from nodestream)

  Downloading uvloop-0.18.0-cp311-cp311-macosx_10_9_x86_64.whl.metadata (4.9 kB)

Collecting botocore<1.33.0,>=1.32.2 (from boto3<2.0.0,>=1.26.137->nodestream)

  Downloading botocore-1.32.2-py3-none-any.whl.metadata (6.1 kB)

Collecting s3transfer<0.8.0,>=0.7.0 (from boto3<2.0.0,>=1.26.137->nodestream)

  Downloading s3transfer-0.7.0-py3-none-any.whl.metadata (1.8 kB)

Collecting crashtest<0.5.0,>=0.4.1 (from cleo<3.0.0,>=2.0.1->nodestream)

  Downloading crashtest-0.4.1-py3-none-any.whl (7.6 kB)

Collecting rapidfuzz<4.0.0,>=3.0.0 (from cleo<3.0.0,>=2.0.1->nodestream)

  Downloading rapidfuzz-3.5.2-cp311-cp311-macosx_10_9_x86_64.whl.metadata (11 kB)

Collecting binaryornot>=0.4.4 (from cookiecutter<3.0.0,>=2.1.1->nodestream)

  Downloading binaryornot-0.4.4-py2.py3-none-any.whl (9.0 kB)

Collecting click<9.0.0,>=7.0 (from cookiecutter<3.0.0,>=2.1.1->nodestream)

  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)

Collecting python-slugify>=4.0.0 (from cookiecutter<3.0.0,>=2.1.1->nodestream)

  Downloading python_slugify-8.0.1-py2.py3-none-any.whl (9.7 kB)

Collecting requests>=2.23.0 (from cookiecutter<3.0.0,>=2.1.1->nodestream)

  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)

Collecting arrow (from cookiecutter<3.0.0,>=2.1.1->nodestream)

  Downloading arrow-1.3.0-py3-none-any.whl.metadata (7.5 kB)

Collecting rich (from cookiecutter<3.0.0,>=2.1.1->nodestream)

  Downloading rich-13.7.0-py3-none-any.whl.metadata (18 kB)

Collecting certifi (from httpx<0.25.0,>=0.24.1->nodestream)

  Downloading certifi-2023.7.22-py3-none-any.whl.metadata (2.2 kB)

Collecting httpcore<0.18.0,>=0.15.0 (from httpx<0.25.0,>=0.24.1->nodestream)

  Downloading httpcore-0.17.3-py3-none-any.whl.metadata (18 kB)

Collecting idna (from httpx<0.25.0,>=0.24.1->nodestream)

  Downloading idna-3.4-py3-none-any.whl (61 kB)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 2.1 MB/s eta 0:00:00

Collecting sniffio (from httpx<0.25.0,>=0.24.1->nodestream)

  Downloading sniffio-1.3.0-py3-none-any.whl (10 kB)

Collecting MarkupSafe>=2.0 (from Jinja2<4,>=3->nodestream)

  Downloading MarkupSafe-2.1.3-cp311-cp311-macosx_10_9_x86_64.whl.metadata (3.0 kB)

Collecting pytz (from neo4j<6.0.0,>=5.8.0->nodestream)

  Downloading pytz-2023.3.post1-py2.py3-none-any.whl.metadata (22 kB)

Collecting numpy<2,>=1.23.2 (from pandas<3,>=2->nodestream)

  Downloading numpy-1.26.2-cp311-cp311-macosx_10_9_x86_64.whl.metadata (61 kB)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 1.9 MB/s eta 0:00:00

Collecting python-dateutil>=2.8.2 (from pandas<3,>=2->nodestream)

  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 8.2 MB/s eta 0:00:00

Collecting tzdata>=2022.1 (from pandas<3,>=2->nodestream)

  Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 11.4 MB/s eta 0:00:00

Collecting contextlib2>=0.5.5 (from schema<0.8.0,>=0.7.5->nodestream)

  Downloading contextlib2-21.6.0-py2.py3-none-any.whl (13 kB)

Collecting docker>=4.0.0 (from testcontainers<4.0.0,>=3.7.1->testcontainers[neo4j]<4.0.0,>=3.7.1->nodestream)

  Downloading docker-6.1.3-py3-none-any.whl.metadata (3.5 kB)

Collecting wrapt (from testcontainers<4.0.0,>=3.7.1->testcontainers[neo4j]<4.0.0,>=3.7.1->nodestream)

  Downloading wrapt-1.16.0-cp311-cp311-macosx_10_9_x86_64.whl.metadata (6.6 kB)

Collecting deprecation (from testcontainers<4.0.0,>=3.7.1->testcontainers[neo4j]<4.0.0,>=3.7.1->nodestream)

  Downloading deprecation-2.1.0-py2.py3-none-any.whl (11 kB)

Collecting chardet>=3.0.2 (from binaryornot>=0.4.4->cookiecutter<3.0.0,>=2.1.1->nodestream)

  Downloading chardet-5.2.0-py3-none-any.whl.metadata (3.4 kB)

Collecting urllib3<2.1,>=1.25.4 (from botocore<1.33.0,>=1.32.2->boto3<2.0.0,>=1.26.137->nodestream)

  Downloading urllib3-2.0.7-py3-none-any.whl.metadata (6.6 kB)

Collecting packaging>=14.0 (from docker>=4.0.0->testcontainers<4.0.0,>=3.7.1->testcontainers[neo4j]<4.0.0,>=3.7.1->nodestream)

  Downloading packaging-23.2-py3-none-any.whl.metadata (3.2 kB)

Collecting websocket-client>=0.32.0 (from docker>=4.0.0->testcontainers<4.0.0,>=3.7.1->testcontainers[neo4j]<4.0.0,>=3.7.1->nodestream)

  Downloading websocket_client-1.6.4-py3-none-any.whl.metadata (7.7 kB)

Collecting h11<0.15,>=0.13 (from httpcore<0.18.0,>=0.15.0->httpx<0.25.0,>=0.24.1->nodestream)

  Downloading h11-0.14.0-py3-none-any.whl (58 kB)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 2.0 MB/s eta 0:00:00

Collecting anyio<5.0,>=3.0 (from httpcore<0.18.0,>=0.15.0->httpx<0.25.0,>=0.24.1->nodestream)

  Downloading anyio-4.0.0-py3-none-any.whl.metadata (4.5 kB)

Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas<3,>=2->nodestream)

  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)

Collecting text-unidecode>=1.3 (from python-slugify>=4.0.0->cookiecutter<3.0.0,>=2.1.1->nodestream)

  Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.2/78.2 kB 2.6 MB/s eta 0:00:00

Collecting charset-normalizer<4,>=2 (from requests>=2.23.0->cookiecutter<3.0.0,>=2.1.1->nodestream)

  Downloading charset_normalizer-3.3.2-cp311-cp311-macosx_10_9_x86_64.whl.metadata (33 kB)

Collecting types-python-dateutil>=2.8.10 (from arrow->cookiecutter<3.0.0,>=2.1.1->nodestream)

  Downloading types_python_dateutil-2.8.19.14-py3-none-any.whl.metadata (1.6 kB)

Collecting markdown-it-py>=2.2.0 (from rich->cookiecutter<3.0.0,>=2.1.1->nodestream)

  Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)

Collecting pygments<3.0.0,>=2.13.0 (from rich->cookiecutter<3.0.0,>=2.1.1->nodestream)

  Downloading Pygments-2.16.1-py3-none-any.whl.metadata (2.5 kB)

Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->cookiecutter<3.0.0,>=2.1.1->nodestream)

  Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)

Downloading nodestream-0.8.20-py3-none-any.whl (108 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.5/108.5 kB 3.7 MB/s eta 0:00:00

Downloading cymple-0.8.1-py2.py3-none-any.whl (11 kB)

Downloading boto3-1.29.2-py3-none-any.whl (135 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.8/135.8 kB 4.9 MB/s eta 0:00:00

Downloading cleo-2.1.0-py3-none-any.whl (78 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.7/78.7 kB 2.5 MB/s eta 0:00:00

Downloading confluent_kafka-2.3.0-cp311-cp311-macosx_10_9_x86_64.whl (3.4 MB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 24.3 MB/s eta 0:00:00

Downloading cookiecutter-2.4.0-py3-none-any.whl (38 kB)

Downloading httpx-0.24.1-py3-none-any.whl (75 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.4/75.4 kB 2.7 MB/s eta 0:00:00

Downloading pandas-2.1.3-cp311-cp311-macosx_10_9_x86_64.whl (11.6 MB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 30.6 MB/s eta 0:00:00

Downloading psutil-5.9.6-cp36-abi3-macosx_10_9_x86_64.whl (246 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 246.1/246.1 kB 7.9 MB/s eta 0:00:00

Downloading uvloop-0.18.0-cp311-cp311-macosx_10_9_x86_64.whl (1.5 MB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 25.7 MB/s eta 0:00:00

Downloading botocore-1.32.2-py3-none-any.whl (11.4 MB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 41.3 MB/s eta 0:00:00

Downloading click-8.1.7-py3-none-any.whl (97 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 kB 3.1 MB/s eta 0:00:00

Downloading docker-6.1.3-py3-none-any.whl (148 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.1/148.1 kB 5.4 MB/s eta 0:00:00

Downloading httpcore-0.17.3-py3-none-any.whl (74 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.5/74.5 kB 2.6 MB/s eta 0:00:00

Downloading MarkupSafe-2.1.3-cp311-cp311-macosx_10_9_x86_64.whl (13 kB)

Downloading numpy-1.26.2-cp311-cp311-macosx_10_9_x86_64.whl (20.6 MB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.6/20.6 MB 37.9 MB/s eta 0:00:00

Downloading pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 502.5/502.5 kB 14.8 MB/s eta 0:00:00

Downloading rapidfuzz-3.5.2-cp311-cp311-macosx_10_9_x86_64.whl (2.6 MB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 30.7 MB/s eta 0:00:00

Downloading requests-2.31.0-py3-none-any.whl (62 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 1.8 MB/s eta 0:00:00

Downloading certifi-2023.7.22-py3-none-any.whl (158 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.3/158.3 kB 5.7 MB/s eta 0:00:00

Downloading s3transfer-0.7.0-py3-none-any.whl (79 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.8/79.8 kB 2.9 MB/s eta 0:00:00

Downloading arrow-1.3.0-py3-none-any.whl (66 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 kB 2.2 MB/s eta 0:00:00

Downloading rich-13.7.0-py3-none-any.whl (240 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 240.6/240.6 kB 8.6 MB/s eta 0:00:00

Downloading wrapt-1.16.0-cp311-cp311-macosx_10_9_x86_64.whl (37 kB)

Downloading anyio-4.0.0-py3-none-any.whl (83 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.1/83.1 kB 3.0 MB/s eta 0:00:00

Downloading chardet-5.2.0-py3-none-any.whl (199 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.4/199.4 kB 6.4 MB/s eta 0:00:00

Downloading charset_normalizer-3.3.2-cp311-cp311-macosx_10_9_x86_64.whl (121 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.4/121.4 kB 4.5 MB/s eta 0:00:00

Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 kB 3.2 MB/s eta 0:00:00

Downloading packaging-23.2-py3-none-any.whl (53 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 kB 1.8 MB/s eta 0:00:00

Downloading Pygments-2.16.1-py3-none-any.whl (1.2 MB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 23.8 MB/s eta 0:00:00

Downloading types_python_dateutil-2.8.19.14-py3-none-any.whl (9.4 kB)

Downloading urllib3-2.0.7-py3-none-any.whl (124 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 kB 4.5 MB/s eta 0:00:00

Downloading websocket_client-1.6.4-py3-none-any.whl (57 kB)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 1.9 MB/s eta 0:00:00

Building wheels for collected packages: neo4j

  Building wheel for neo4j (pyproject.toml) ... done

  Created wheel for neo4j: filename=neo4j-5.14.1-py3-none-any.whl size=267560 sha256=f9e3142b266bae4d030d0875ab2e4356110efee4eb1843bd8523658f4ba6a7b3

  Stored in directory: /Users/suzy/Library/Caches/pip/wheels/da/1c/41/0330aeed780638bb8d232e94fffed164de968d778f8ebb3d23

Successfully built neo4j

Installing collected packages: types-python-dateutil, text-unidecode, pytz, confluent-kafka, wrapt, websocket-client, uvloop, urllib3, tzdata, sniffio, six, rapidfuzz, python-slugify, python-json-logger, pygments, psutil, packaging, numpy, neo4j, mdurl, MarkupSafe, jmespath, idna, h11, cymple, crashtest, contextlib2, click, charset-normalizer, chardet, certifi, schema, requests, python-dateutil, markdown-it-py, Jinja2, deprecation, cleo, binaryornot, anyio, rich, pandas, httpcore, docker, botocore, arrow, testcontainers, s3transfer, httpx, cookiecutter, boto3, nodestream

ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/usr/local/LICENSE.txt'

Consider using the `--user` option or check the permissions.

**Expected behavior**

I expect that install scripts would not alter files in protected locations

**Comment by zprobst** [comment]
Hi @patmoore  👋 

Thanks for submitting this.  If you are directly doing `pip install` this appears at first blush to be expected behavior. When you are doing a `pip install`, its by default installing it across the system. I'm afraid that that is less of a `nodestream` issue and more of how python packaging works. 

Generally its advisable to install any python package inside of a virtual environment or at the very least install it for the user (hence why `--user` is recommended to you by pip). I think clarification of this point in the getting started documentation is warranted. 

Given that context, do you agree? Do you have any other recommendations?

**Comment by zprobst** [comment]
I believe this is not a central issue with nodestream. Hence, closing
