### ISSUE TITLE
[BUG] nodestream remove command wipes the config sections

### ISSUE THREAD

**Issue by ccloes** [nodestream-proj/nodestream#188]
**Describe the bug**
When running the nodestream remove pipeline command wipes the config values out of the pipeline yaml file.

**To Reproduce**

1. Update your nodestream.yaml file with targets etc after the pipelines
2. Run the following

`poetry run nodestream remove default sample`

**Expected behavior**
The yaml file should only remove the pipeline section and leave the config.

**Comment by stuartio** [comment]
Steps:

1. Update your nodestream.yaml file with targets etc after the pipelines
2. run the following

`poetry run nodestream remove default sample`

**Comment by zprobst** [comment]
Schedule for fixing in `0.10.0`
