### ISSUE TITLE
parallel is misspelled in query.py

### ISSUE THREAD

**Issue by davidlrosenblum** [nodestream-proj/nodestream#28]
**Describe the bug**
parallel is mis-spelled - false is the default, so this would probably work as intended.
    {batchsize: 1000, paralell: false, retries: 3, params: {batched_parameter_sets: $batched_parameter_sets}}

**Expected behavior**
should be
    {batchsize: 1000, parallel: false, retries: 3, params: {batched_parameter_sets: $batched_parameter_sets}}

**Comment by zprobst** [comment]
Thanks for catching that @davidlrosenblum. We've correct it 👍
