### ISSUE TITLE
[REQUEST] Support Database/Pipeline Migrations

### ISSUE THREAD

**Issue by zprobst** [nodestream-proj/nodestream#36]
Original Idea from @ccloes, iteration by @zprobst 

**Is your feature request related to a problem? Please describe.**
As your data and pipelines evolve, there is need to update your database to match the new schema and new data. Broadly speaking there are two types of migrations needed:

1. Non-Material Differences (Simple db operations can transmute the existing data in place)
    - key field renames
    - property field renames
    - type renames
    - additional type adds
    - additional type removals
    - removing nodes/relationships
  
2. Material Differences (The data must be rerun through the pipeline)
   - adding nodes/relationships
   - adding new properties
   - adding to the node/rel key 

The solution for each one of these is different and is often error prone. While there is a lot of maturity in relational database migration, there lacks the same sophistication in Graph Databases. Despite graph databases broadly being schema-less most applications still require/expect a certain schema and thus ensuring consistency is important. 

**Describe the solution you'd like**
Drawing on the work done from relational database world as well as the graph database world, as pipelines change, data should be able to be migrated from one schema to the next. Allowing users to supply defaults. Ideally the solution would mirror similar approaches taken by other Database Migration systems, perhaps by introducing a series of commands that could work like this:

- `nodestream migrations make` - diff the current state and produce a list of operations that are needed to be performed. 
- `nodestream migrations migrate` - run the operations that need to be performed against the database - storing the state of the migrations in the dbms somewhere. 

This requires design on how we can infer the deltas between two states in the pipeline, designing the API for new database connectors to operate on, an defining how migrations are stored, loaded, and built from within the pipeline. 

**Additional context**

Prior Art:
- [Django Migrations](https://docs.djangoproject.com/en/4.2/topics/migrations/)
- [Active Record Migrations (RoR)](https://guides.rubyonrails.org/active_record_migrations.html)
- [Neo4j-Migrations](https://neo4j.com/labs/neo4j-migrations/)

**Comment by zprobst** [comment]
I have some working code for this issue. Some branches will start to appear on this topic.

**Comment by michael-simons** [comment]
Hej, author of Neo4j Migrations here.

a) Neo4j Migrations could run your Cypher in a controlled and repeatable fashion (its main purpose)
b) Neo4j Migration has some of your suggested refactoring already build in.

We can generate Cypher for

- adding surrogate keys (that is, finding a set of nodes / relationships and add an `id` or otherwise named property containing a unique, generated value
- merging a set of nodes into one node
- normalize properties (i.e. `0`, `"falsch"`, `"FALSE"`, `f` etc  normalized to `false`)
- renaming labels and types over the whole graph

Here's more info https://michael-simons.github.io/neo4j-migrations/2.9.0/#appendix_refactorings

Happy to provide more information and background.

**Comment by fbiville** [comment]
An extra data point for prior art solutions: https://www.neo4j.com/labs/liquibase/docs/.

**Comment by zprobst** [comment]
Initial versions deployed in 0.12. Closing this issue in favor of the label: https://github.com/nodestream-proj/nodestream/issues?q=is%3Aissue+is%3Aopen+label%3AMigrations
