### ISSUE TITLE
[BUG] Installation on Windows fails

### ISSUE THREAD

**Issue by stuartio** [nodestream-proj/nodestream#75]
Nodestream requires jq, which has no install candidate for Windows, and fails. User _could_ use WSL, but native Windows support would be appreciated. Is there another json processor which could perform the functions of jq which is cross-platform compatible?

**To Reproduce**
1. run `poetry install` on Windows 10/11

**Expected behavior**
No errors

**Additional context**
```
Building wheels for collected packages: jq, neo4j
  Building wheel for jq (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for jq (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      pip_system_certs: ERROR: could not register module: No module named 'wrapt'
      running bdist_wheel
      running build
      running build_ext
      Executing: ./configure CFLAGS=-fPIC --prefix=C:\Users\Stuart\AppData\Local\Temp\pip-install-v59tbaak\jq_7db0ed1eeac7435e9e813496d9b21bbf\_deps\build\onig-install-6.9.4
      error: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for jq
  Building wheel for neo4j (pyproject.toml) ... done
  Created wheel for neo4j: filename=neo4j-5.11.0-py3-none-any.whl size=259816 sha256=5821ac0cb5a58eebe937e6baea053839d8b739ae3fca20b463fec8ca9c11e4da
  Stored in directory: c:\users\stuart\appdata\local\pip\cache\wheels\1c\36\cb\72001d55a7e428adca30886ee6314c7b4fdd49d9fdd98ae7e3
```
This site, as well as poetry.lock doesn't mention Windows support https://pypi.org/project/jq/

**Comment by zprobst** [comment]
Thanks for the bug report @stuartio 

this intertwines nicely with #19. I added JQ as a nice to have. But since we have jmespath and this is now the second issue with this dependency. I am content with remove it from the core library to solve both of these issues.
