### ISSUE TITLE
[BUG] import resource not applicable on Windows

### ISSUE THREAD

**Issue by stuartio** [nodestream-proj/nodestream#76]
**Describe the bug**
`import resource` does not function on Windows

**To Reproduce**
Any project run which uses pipeline_progress_report.py will fail on Windows

**Expected behavior**
Some other method is used in the get_max_mem_md() function, or it simply returns 0 on Windows, and the import statement is scoped based on OS

**Comment by zprobst** [comment]
We have implemented Cross Platform compatiblity in #107
